[workspace]
members = [
    "crates/api",
    "crates/bundle",
    "crates/cdn",
    "crates/connections",
    "crates/gateway",
    "crates/events",
    "crates/util/config",
    "crates/util/db",
    "crates/util/util",
    "crates/webrtc",
]
resolver = "2"
